@startuml
title アクティビティ図(PlantUMLにて作成) 

(*) ->"色を入力"
 note right: カラーチップ指定 \n xyYを入力 \n Labを入力

if "入力完了?" then
 ->[yes] "XYZ値算出"
else
 ->[no] "色を入力"
endif

"XYZ値算出" -->"二色型色覚を再現"
	
"二色型色覚を再現" -->"Lab値算出"
	
"Lab値算出" -->"色差算出"
 note right: 二色型色覚の状態で色差を計算
	
"色差算出" -->"色差と色弁別閾値を比較"
 note right: 色弁別閾値は可変
	
"色差と色弁別閾値を比較" -->"結果表示"

if "すべての組みあわせで計算完了?" then
  ->[yes] (*)
else
  ->[no] "色差算出"
endif

@enduml