@startuml
title ユースケース図(PlantUMLにて作成) 

' アクター
actor ユーザ

' 関連
rectangle 二色型色覚チェッカー{
	
	usecase (色度値を入力)
	usecase (カラーチップを指定)
	usecase (色の組み合わせチェック)
	note left : 組み合わせチェックを行うために \n 色の指定が必要

	ユーザ --> (色度値を入力)
	ユーザ --> (カラーチップを指定)

	(色の組み合わせチェック) ..> (色度値を入力): <<include>>
	(色の組み合わせチェック) ..> (カラーチップを指定): <<include>>
}
@enduml